
server:
  port: 8090
  servlet:
    context-path: /find-cloud-oauth2

app:
  server:
    domain: localhost
    url: http://${app.server.domain}:${server.port}${server.servlet.context-path}

spring:
  application:
    name: find-cloud-oauth2
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/voyager
    username: root
    password: 123456

