swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0
  try-host: http://${app.server.domain}:${server.port}${server.servlet.context-path}
