
spring:
  application:
    name: fing-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 120.26.203.172:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: find-cloud-user
          uri: lb://find-cloud-user
          predicates:
            - Path=/find-cloud-user/**
        - id: find-cloud-oauth2
          uri: lb://find-cloud-oauth2
          predicates:
            - Path=/find-cloud-oauth2/**

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.203.172:3306/voyager
    username: turnglight
    password: Dyn900209!@#$
    pool:
      validation-query: SELECT 1
      enabled: true

oauth2:
  cloud:
    sys:
      parameter:
        ignoreUrls:
          - /oauth/token
          - /oauth/authorize
          - /find-cloud-user/third/jiguang/verification
