
spring:
  application:
    name: fing-cloud-gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: find-cloud-user
          uri: lb://find-cloud-user
          predicates:
            - Path=/find-cloud-user/**
        - id: find-cloud-oauth2
          uri: lb://find-cloud-oauth2
          predicates:
            - Path=/find-cloud-oauth2/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/voyager
    username: root
    password: 123456
    pool:
      validation-query: SELECT 1
      enabled: true
