
spring:
  application:
    name: fing-cloud-gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: find-cloud-user
          uri: lb://find-cloud-user
          predicates:
            - Path=/find-cloud-user/**
  r2dbc:
    host: 127.0.0.1
    port: 3306
    database: voyager
    url: r2dbc:mysql://${spring.r2dbc.host}:${spring.r2dbc.port}/${spring.r2dbc.database}?zeroDate=use_round
    username: root
    password: 123456
    pool:
      validation-query: SELECT 1
      enabled: true
