

server:
  port: 8091

spring:
  application:
    name: find-cloud-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/voyager
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 500
        max-wait: -1
    timeout: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    banner: false
    db-config:
      table-underline: true
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true

ali:
  accessKeyID: LTAI5t8C3h3hoSBnA9aJaMaR
  accessKeySecret: uIfqkIC4C9a2Xy7nd61SFLLkacbulc

jiguang:
  api:
    appKey: 96af57a8b5ed5954a5e0bd46
    masterSecret: 13536dad90aafa4c93cec389
    # 提交loginToken，验证后返回手机号码
    loginTokenVerifyUrl: https://api.verification.jpush.cn/v1/web/loginTokenVerify
    # 提交手机号码和token，验证是否一致
    verifyUrl: https://api.verification.jpush.cn/v1/web/verify
    # 自定义标识
    extId: turnglight
    # RSA私钥
    privateKey:
    #RSA公钥
    publicKey:

