
server:
  port: 8091
  servlet:
    context-path: /find-cloud-user

app:
  server:
    domain: localhost
    url: http://${app.server.domain}:${server.port}${server.servlet.context-path}

spring:
  application:
    name: find-cloud-user
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/voyager
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 500
        max-wait: -1
    timeout: 0

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0
  try-host: http://${app.server.domain}:${server.port}${server.servlet.context-path}

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    banner: false
    db-config:
      table-underline: true
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
